routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [App\Http\Controllers\HomepageController::class, 'index']);
Route::get('greasy_spoon/menu', [App\Http\Controllers\HomepageController::class, 'menu']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('admin/home', [App\Http\Controllers\HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Route::resource('admin/home/booking', App\Http\Controllers\BookingController::class);
Route::resource('admin/home/menu', App\Http\Controllers\MenuController::class);
Route::get('admin/home/menu/activate/{id}', [App\Http\Controllers\MenuController::class,'activate']);
Route::get('admin/home/menu/deactivate/{id}', [App\Http\Controllers\MenuController::class,'deactivate']);
Route::get('admin/home/{id}', [App\Http\Controllers\HomeController::class, 'confirmed']);
Route::get('admin/greasy_kitchen/message', [App\Http\Controllers\ContactUsController::class, 'message']);
Route::resource('greasy_spoon/contact', App\Http\Controllers\ContactUsController::class);
Route::get('/greasy_spoon/home-cook', [App\Http\Controllers\HomepageController::class, 'homeCook']);

resources/views/adminHome.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-11">
            <table class="table table-striped" id="mydata">
                <thead>
                    <tr class="text-white table">
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Contact Number</th>
                        <th>No of Guests</th>
                        <th>Date and Time</th>
                        <th>Request</th>
                        <th style="text-align: right;">Actions</th>
                    </tr>
                </thead>
                <tbody>

                        @foreach($bookings as $booking)
                        <tr>
                        <td>{{$booking->id}}</td>
                        <td>{{$booking->name}}</td>
                        <td>{{$booking->email}}</td>
                        <td>{{$booking->contact_number}}</td>
                        <td>{{$booking->guest}}</td>
                        <td>{{$booking->date}} {{$booking->time}}</td>
                        <td>{{$booking->request}}</td>
                        @if($booking->is_accepted == 0)
                           <td> <a href="/home/{{$booking->id}}"><button class="btn btn-success">Confirm</button></a></td>

                        @elseif($booking->is_accepted == 1)
                            <td>Confirmed</td>

                        @endif
                    </tr>
                        @endforeach



                </tbody>

            </table>

        </div>
    </div>
</div>
@endsection

resources/views/admin_message.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-11">
            <table class="table table-striped" id="mydata">
                <thead>
                    <tr class=" table text-white">
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Contact Number</th>
                        <th>Message</th>

                    </tr>
                </thead>
                <tbody>

                        @foreach($messages as $message)
                        <tr>
                        <td>{{$message->id}}</td>
                        <td>{{$message->name}}</td>
                        <td>{{$message->email}}</td>
                        <td>{{$message->contact_number}}</td>
                        <td>{{$message->message}}</td>



                    </tr>
                        @endforeach



                </tbody>

            </table>

        </div>
    </div>
</div>
@endsection

resources/views/contact.blade.php
@include('layouts/header')
    {{-- <div class="container" style="width: 100%"> --}}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="/"><img src="/images/icon.png" alt="" style="height: 60px; width:200px"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/"><i class="fas fa-home"></i> Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/greasy_spoon/menu"><i class="fas fa-bars"></i> Menu</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="/greasy_spoon/contact"><i class="fas fa-id-card"></i> Contact Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/greasy_spoon/home-cook"><i class="fas fa-blender"></i> Home Cook</a>
                  </li>
                  {{-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown link
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li> --}}
                </ul>
              </div>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}"><i class="fas fa-sign-in-alt"></i> {{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}"><i class="fas fa-sign-in-alt"></i> {{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @if(Auth::user()->is_admin==0)
                                <a class="dropdown-item" href="/home"
                                       >
                                        {{ __('MY Bookings') }}
                                    </a>
                                    @endif
                                    @if(Auth::user()->is_admin==1)
                                <a class="dropdown-item" href="/admin/home"
                                       >
                                        {{ __('Admin Panel') }}
                                    </a>
                                    @endif
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>


            </div>
        </nav>

        <div class="container pt-4">
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-10">
                        <h4>Contact Us</h4>
                        <form class="" method="POST" action="{{ route('contact.store') }}">
                            @csrf
                            <div class="col-md-12">
                                @if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>

                            @endif
                            @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

                            </div>

                            <div class="col-md-6">
                              <label for="inputEmail4" class="form-label">Name</label>
                              <input type="name" name="name" value="{{old('name')}}" class="form-control" placeholder="Enter your Name" id="inputName4" required>
                            </div>
                            <div class="col-md-6">
                              <label for="inputEmail" class="form-label">Email</label>
                              <input type="email" name="email" value="{{old('email')}}" class="form-control" placeholder="Enter your Email" id="inputEmail4" required>
                            </div>
                            <div class="col-6">
                              <label for="inputAddress" class="form-label">Contact Number</label>
                              <input type="text" class="form-control" value="{{old('contact_number')}}" name="contact_number" id="inputAddress" placeholder="Contact Nmuber" required>
                            </div>

                              <div class="col-md-12">
                                <label for="inputCity" class="form-label">Message</label>
                                <textarea name="message" class="form-control" id="message" cols="30" rows="5">Enter your message</textarea>
                                {{-- <input type="time" name="time" class="form-control" name="date" id="inputCity" required> --}}
                              </div>

                            <div class="col-12 pt-4">
                              <button type="submit" class="btn btn-primary booking_button_down col-12">Submit Message</button>
                            </div>
                          </form>
                    </div>
                    <div class="col-md-2">

                    </div>
                </div>
            </div>
        </div>

        <div class="container text-center pt-5 pb-3">
            <p class=" border-top border-bottom pt-1 pb-1">Copyright © 2021 Greasy Kitchen. all rights reserved.</p>
        </div>


</body>
</html>

resources/views/home.blade.php
@extends('layouts.u_app')

@section('content')
<div class="container">
    <div class="row">

        <button type="btn" onclick="location.href='/'" class="btn btn-primary col-md-3 mb-3">Book a Table</button>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="card">
                <div class="card-header">
                    Bookings List
                </div>
                <div class="card-body">
                    <table class="table table-striped" id="mydata">
                        @if($bookings->count()>0)
                        <thead>
                            <tr class="table text-white">
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Contact Number</th>
                                <th>No of Guests</th>
                                <th>Date and Time</th>
                                <th>Request</th>
                                <th style="text-align: right;">Decision</th>
                            </tr>
                        </thead>
                        <tbody>

                                @foreach($bookings as $booking)
                                <tr>
                                <td>{{$booking->id}}</td>
                                <td>{{$booking->name}}</td>
                                <td>{{$booking->email}}</td>
                                <td>{{$booking->contact_number}}</td>
                                <td>{{$booking->guest}}</td>
                                <td>{{$booking->date}} {{$booking->time}}</td>
                                <td>{{$booking->request}}</td>
                                @if($booking->is_accepted == 0)
                                    <td>Pending</td>

                                @elseif($booking->is_accepted == 1)
                                    <td>Confirmed</td>

                                @endif
                            </tr>
                                @endforeach


                        </tbody>
                        @else
                        <h3>No Bookings Record</h3>

                        @endif
                    </table>
                </div>
            </div>


        </div>
    </div>
</div>
@endsection

resources/views/home_cook.blade.php
@include('layouts/header')
    {{-- <div class="container" style="width: 100%"> --}}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#"><img src="/images/icon.png" alt="" style="height: 60px; width:200px"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/"><i class="fas fa-home"></i> Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/greasy_spoon/menu"><i class="fas fa-bars"></i> Menu</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/greasy_spoon/contact"><i class="fas fa-id-card"></i> Contact Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="/greasy_spoon/home-cook"><i class="fas fa-id-card"></i> Home Cook</a>
                  </li>
                  {{-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown link
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li> --}}
                </ul>
              </div>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}"><i class="fas fa-sign-in-alt"></i> {{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}"><i class="fas fa-sign-in-alt"></i> {{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @if(Auth::user()->is_admin==0)
                                <a class="dropdown-item" href="/home"
                                       >
                                        {{ __('MY Bookings') }}
                                    </a>
                                    @endif
                                    @if(Auth::user()->is_admin==1)
                                <a class="dropdown-item" href="/admin/home"
                                       >
                                        {{ __('Admin Panel') }}
                                    </a>
                                    @endif
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>


            </div>
        </nav>
        <div class="jumbotron">
            <h4>Future Works</h4>
            <p>This page home cooks will contain the number of grocery items which are used to cook delicious food in our kitchen.
                People can dirsectly buy the goods from here which will be either home delivered or pick up from the store.
            </p>
            <p>
                Furthermore, with the integration of online payment gateway, people can pay online for their shopping.
            </p>

        </div>

        <div class="container text-center pt-5 pb-3">
            <p class=" border-top border-bottom pt-1 pb-1">Copyright © 2021 Greasy Kitchen. all rights reserved.</p>
        </div>


</body>
</html>

resources/views/menu.blade.php
@include('layouts/header')
    {{-- <div class="container" style="width: 100%"> --}}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="/"><img src="/images/icon.png" alt="" style="height: 60px; width:200px"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/"><i class="fas fa-home"></i> Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="/greasy_spoon/menu"><i class="fas fa-bars"></i> Menu</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/greasy_spoon/contact"><i class="fas fa-id-card"></i> Contact Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/greasy_spoon/home-cook"><i class="fas fa-blender"></i> Home Cook</a>
                  </li>
                  {{-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown link
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li> --}}
                </ul>
              </div>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}"><i class="fas fa-sign-in-alt"></i> {{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}"><i class="fas fa-sign-in-alt"></i> {{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @if(Auth::user()->is_admin==0)
                                <a class="dropdown-item" href="/home"
                                       >
                                        {{ __('MY Bookings') }}
                                    </a>
                                    @endif
                                    @if(Auth::user()->is_admin==1)
                                <a class="dropdown-item" href="/admin/home"
                                       >
                                        {{ __('Admin Panel') }}
                                    </a>
                                    @endif
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>


            </div>
        </nav>

        <div class="container col-md-7 pt-4">
            <h4>Greasy Spoon : Menu Lists</h4>
            <div class="border-bottom mb-4"><h5>Appetizers</h5>
                @foreach($appetizers as $appetizer)
                    <h5 class="mt-3 px-3">{{$appetizer->dish_name}} <span style="letter-spacing: 4px;">...........................................................................</span> ${{$appetizer->dish_price}}</h5>
                    <p class="px-3">{{$appetizer->dish_description}}</p>
                @endforeach
            </div>

            <div class="border-bottom mb-4">
                <h5>Main Dish</h5>
                @foreach($mains as $main)
                    <h5 class="mt-3 px-3">{{$main->dish_name}} <span style="letter-spacing: 4px;">...........................................................................</span> ${{$main->dish_price}}</h5>
                    <p class="px-3">{{$main->dish_description}}</p>
                @endforeach
            </div>

            <div class="border-bottom mb-4">
            <h5>Desserts</h5>
                @foreach($desserts as $dessert)
                    <h5 class="mt-3 px-3">{{$dessert->dish_name}} <span style="letter-spacing: 4px;">...........................................................................</span> ${{$dessert->dish_price}}</h5>
                    <p class="px-3">{{$dessert->dish_description}}</p>
                @endforeach
            </div>

        </div>

        <div class="container text-center pt-5 pb-3">
            <p class=" border-top border-bottom pt-1 pb-1">Copyright © 2021 Greasy Spoon. all rights reserved.</p>
        </div>


</body>
</html>