routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [App\Http\Controllers\HomepageController::class, 'index']);
Route::get('greasy_spoon/menu', [App\Http\Controllers\HomepageController::class, 'menu']);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('admin/home', [App\Http\Controllers\HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Route::resource('admin/home/booking', App\Http\Controllers\BookingController::class);
Route::resource('admin/home/menu', App\Http\Controllers\MenuController::class);
Route::get('admin/home/menu/activate/{id}', [App\Http\Controllers\MenuController::class,'activate']);
Route::get('admin/home/menu/deactivate/{id}', [App\Http\Controllers\MenuController::class,'deactivate']);
Route::get('admin/home/{id}', [App\Http\Controllers\HomeController::class, 'confirmed']);
Route::get('admin/greasy_kitchen/message', [App\Http\Controllers\ContactUsController::class, 'message']);
Route::resource('greasy_spoon/contact', App\Http\Controllers\ContactUsController::class);
Route::get('/greasy_spoon/home-cook', [App\Http\Controllers\HomepageController::class, 'homeCook']);

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MenuModel;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = MenuModel::All();
        return view('menu.view_menu')->with('menus', $menus);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('menu.create_menu');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate([
            'dish_type' => 'required',
            'dish_name' => 'required',
            'dish_description' => 'required',
            'dish_price' => 'required',


        ]);

            MenuModel::create($request->all());
            return redirect()->route('menu.index')->with('success', 'Menu Created Sucessfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $menus = MenuModel::find($id);
        return view('menu.edit_menu')->with('menus', $menus);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = $request->validate([
            'dish_type' => 'required',
            'dish_name' => 'required',
            'dish_description' => 'required',
            'dish_price' => 'required',


        ]);
        $menu= MenuModel::find($id);
        $menu->dish_type = $request->input('dish_type');
        $menu->dish_name = $request->input('dish_name');
        $menu->dish_description = $request->input('dish_description');
        $menu->dish_price = $request->input('dish_price');

            $menu->save();
            return redirect()->route('menu.index')->with('success', 'Menu created sucessfully');
    }
    public function activate($id, Request $request)
    {
        $menu = MenuModel::find($id);
        $menu->is_choice = 1;
        $menu->save();
        return redirect()->back()->with('success', 'Menu Activated Sucessfully');
    }
    public function deactivate($id, Request $request)
    {
        $menu = MenuModel::find($id);
        $menu->is_choice = 0;
        $menu->save();
        return redirect()->back()->with('success', 'Menu Deactivated Sucessfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/menu/create_menu.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-11">
<div class="row">

    <button type="btn" onclick="location.href='/admin/home/menu'" class="btn btn-primary col-md-3 mb-3">View Menu</button>
</div>


            <div class="card">

            <div class="card-header">
                Create Menu
            </div>
            <div class="card-body">
                <form method="POST" action="/admin/home/menu">
                    @csrf
                    <div class="col-md-12">
                        <label for="inputEmail4" class="form-label">Dish Type</label>
                        <input type="name" name="dish_type" value="{{old('dish_type')}}" class="form-control" placeholder="Enter Dish Type" id="inputName4" required>
                    </div>
                    <div class="col-md-12">
                        <label for="inputEmail4" class="form-label">Dish Name</label>
                        <input type="name" name="dish_name" value="{{old('dish_type')}}" class="form-control" placeholder="Enter Dish Name" id="inputName4" required>
                    </div>
                    <div class="col-md-12">
                        <label for="inputEmail4" class="form-label">Dish Description</label>
                        <input type="name" name="dish_description" value="{{old('dish_type')}}" class="form-control" placeholder="Enter Dish Description" id="inputName4" required>
                    </div>
                    <div class="col-md-12">
                        <label for="inputEmail4" class="form-label">Dish Price</label>
                        <input type="name" name="dish_price" value="{{old('dish_type')}}" class="form-control" placeholder="Enter Dish Price" id="inputName4" required>
                    </div>
                    <div class="col-md-12 text-center mt-3">
                        <button type="submit" class="btn btn-primary col-md-6">Submit</button>
                    </div>

                  </form>
            </div>
            </div>


        </div>
    </div>
</div>
@endsection

resources/views/menu/edit_menu.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="card">
                <div class="card-header">
                    Edit Menu
                </div>
                <div class="card-body">
                    <form method="POST" action="{{route('menu.update', $menus->id)}}">
                        @csrf
                        @method('PUT')
                        <div class="col-md-12">
                            <label for="inputEmail4" class="form-label">Dish Type</label>
                            <input type="name" name="dish_type" value="{{$menus->dish_type}}" class="form-control" placeholder="Enter your Name" id="inputName4" required>
                        </div>
                        <div class="col-md-12">
                            <label for="inputEmail4" class="form-label">Dish Name</label>
                            <input type="name" name="dish_name" value="{{$menus->dish_name}}" class="form-control" placeholder="Enter your Name" id="inputName4" required>
                        </div>
                        <div class="col-md-12">
                            <label for="inputEmail4" class="form-label">Dish Description</label>
                            <input type="name" name="dish_description" value="{{$menus->dish_description}}" class="form-control" placeholder="Enter your Name" id="inputName4" required>
                        </div>
                        <div class="col-md-12">
                            <label for="inputEmail4" class="form-label">Dish Price</label>
                            <input type="name" name="dish_price" value="{{$menus->dish_price}}" class="form-control" placeholder="Enter your Name" id="inputName4" required>
                        </div>

                        <div class="col-md-12 text-center mt-3">
                            <button type="submit" class="btn btn-primary col-md-6">Submit</button>
                        </div>
                      </form>
                </div>
            </div>


        </div>
    </div>
</div>
@endsection

resources/views/menu/view_menu.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">

        <button type="btn" onclick="location.href='/admin/home/menu/create'" class="btn btn-primary col-md-3 mb-3">Create Menu</button>
    </div>
    <div class="row justify-content-center">

        <div class="col-md-11">
            <table class="table table-striped" id="mydata">
                <thead>
                    <tr class=" table text-white">
                        <th>ID</th>
                        <th>Dish Type</th>
                        <th>Dish Name</th>
                        <th>Dish Description</th>
                        <th>Dish Price</th>
                        <th>Chef's Choice</th>

                        <th style="text-align: right;">Actions</th>
                    </tr>
                </thead>
                <tbody>

                        @foreach($menus as $menu)
                        <tr>
                        <td>{{$menu->id}}</td>
                        <td>{{$menu->dish_type}}</td>
                        <td>{{$menu->dish_name}}</td>
                        <td>{{$menu->dish_description}}</td>
                        <td>{{$menu->dish_price}}</td>
                        @if($menu->is_choice == 0)
                            <td><a href="/admin/home/menu/activate/{{$menu->id}}"><button class="btn btn-success">Activate</button></a></td>

                        @elseif($menu->is_choice == 1)
                            <td><a href="/admin/home/menu/deactivate/{{$menu->id}}"><button class="btn btn-success">Deactivate</button></a></td>

                        @endif



                           <td> <a href="/admin/home/menu/{{$menu->id}}/edit"><button class="btn btn-success">Edit</button></a></td>


                    </tr>
                        @endforeach



                </tbody>

            </table>

        </div>
    </div>
</div>
@endsection